name        : resourceproto
version     : 1.2.0
release     : 4
source      :
    - http://xorg.freedesktop.org/releases/individual/proto/resourceproto-1.2.0.tar.gz : 469029d14fdeeaa7eed1be585998ff4cb92cf664f872d1d69c04140815b78734
license     :
    - MIT
summary     : X Resource Extension
component   : xorg.proto
patterns    : /
description : |
    This extension defines a protocol that allows a client to query the X server about its usage of various resources.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
